### ISSUE TITLE
Don't know how to build task 'redmine:plugins:migrate'

### ISSUE THREAD

**Issue by luk4s** [easysoftware/rys#5]
When I try to migrate redmine plugins from RYS plugin with:
`rake app:redmine:plugins:migrate`
it fails on error:
Don't know how to build task 'redmine:plugins:migrate' (see --tasks)
Did you mean?  app:redmine:plugins:migrate

It seems that problem is in commit - 3277edf9674fd35cd3ff980acad7cf70ffe737ac

**Comment by luk4s** [comment]
Its definitely in it. When I try add "app:" prefix, migrations can be run. But again, it failes after that:
```
Don't know how to build task 'rys:migrate:after_plugins' (see --tasks)
Did you mean?  app:rys:migrate:after_plugins

**Comment by ondra-m** [comment]
Fixed
